# Generated by Django 5.2.5 on 2025-08-10 20:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


def add_testaments(apps, schema_editor):
    Testament = apps.get_model("bible", "Testament")
    Testament.objects.bulk_create(
        [
            Testament(name="OT", order=1),
            Testament(name="NT", order=2),
        ]
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testament",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[("OT", "Old Testament"), ("NT", "New Testament")],
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("order", models.PositiveIntegerField()),
                (
                    "testament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="bible.testament",
                    ),
                ),
            ],
            options={
                "ordering": ("testament__order", "order"),
            },
        ),
        migrations.CreateModel(
            name="Verse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("chapter", models.PositiveIntegerField()),
                ("verse", models.PositiveIntegerField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verses",
                        to="bible.book",
                    ),
                ),
            ],
            options={
                "ordering": ("book__order", "chapter", "verse"),
                "unique_together": {("book", "chapter", "verse")},
            },
        ),
        migrations.RunPython(
            add_testaments,
            reverse_code=migrations.RunPython.noop,
        )
    ]
