# Generated by Django 5.2.5 on 2025-11-30 19:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True, null=True)),
                ("sort_order", models.IntegerField()),
                (
                    "authors",
                    models.ManyToManyField(related_name="books", to="agency.agency"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
