# Generated by Django 5.2.5 on 2025-11-23 22:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField()),
                ('authors', models.ManyToManyField(related_name='books', to='agency.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
