# Generated by Django 5.2.5 on 2025-12-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
