# Generated by Django 5.2.5 on 2025-11-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='words',
            field=models.ManyToManyField(related_name='actors', to='core.word'),
        ),
        migrations.AddField(
            model_name='agency',
            name='persons',
            field=models.ManyToManyField(related_name='acting_as', to='agency.person'),
        ),
    ]
